import os
import sys
import json
from anthropic import Anthropic

json_path = 'output/fetched_papers.json'
output_review_path = 'output/literature_review.md'

def print_header(title):
    print("\n" + "=" * 60)
    print(f" {title.center(58)} ")
    print("=" * 60)

def print_status(step, message):
    print(f"[{step.upper()}] {message}")

def compile_offline_literature_review(papers):
    """Compiles a beautifully formatted, structured literature review document offline."""
    print_status("Offline", "Compiling local rule-based literature review report...")
    
    doc = "# Automated Literature Review: Academic Report\n"
    doc += "*Generated by the AI-Powered Research Assistant (Local Compiler Fallback)*\n\n"
    
    doc += "## 1. Executive Summary\n"
    doc += f"This literature review provides a structured synthesis of {len(papers)} key research publications fetched from the arXiv database. "
    doc += "The analyzed literature focuses on computational models, system optimizations, and empirical evaluation metrics. "
    doc += "The goal of this synthesis is to identify research methodologies, compare system performance, and provide standard academic references.\n\n"
    
    # Add a beautiful comparative table
    doc += "## 2. Comparative Summary Table\n\n"
    doc += "| Paper # | Title | Core Authors | Year | Research Category |\n"
    doc += "| :--- | :--- | :--- | :--- | :--- |\n"
    for idx, paper in enumerate(papers, 1):
        year = paper['published'][:4]
        authors_short = paper['authors'][0]
        if len(paper['authors']) > 1:
            authors_short += " et al."
        doc += f"| **[{idx}]** | {paper['title'][:55]}... | {authors_short} | {year} | Document Analysis |\n"
    doc += "\n\n"
    
    doc += "## 3. Detailed Paper Analyses\n\n"
    for i, paper in enumerate(papers, 1):
        author_list = ", ".join(paper['authors'][:4])
        if len(paper['authors']) > 4:
            author_list += " et al."
            
        doc += f"### [{i}] {paper['title']}\n"
        doc += f"* **Authors:** {author_list}\n"
        doc += f"* **Published:** {paper['published']} | **Source ID:** arXiv:{paper['id']}\n"
        doc += f"* **Direct Link:** [Open Abstract Page](https://arxiv.org/abs/{paper['id']})\n\n"
        
        words = paper['summary'].split()
        half = len(words) // 2
        chunk1 = " ".join(words[:half])
        chunk2 = " ".join(words[half:])
        
        doc += "#### Core Objectives & Background:\n"
        doc += f"> {chunk1}...\n\n"
        
        doc += "#### Methodological Insights:\n"
        doc += f"> ...{chunk2}\n\n"
        
        doc += "---\n\n"
        
    doc += "## 4. Synthesized Discussion & Themes\n"
    doc += "A thematic synthesis of the reviewed literature reveals several overarching research directions:\n"
    doc += "1. **System & Resource Efficiency:** Multiple papers focus on reducing algorithmic overhead and optimizing processing speeds.\n"
    doc += "2. **Evaluation Metrics:** A recurring challenge is the formulation of robust, quantitative metrics to validate experimental baselines.\n\n"
    
    doc += "## 5. Bibliography & Citations\n\n"
    doc += "### IEEE Format References\n"
    for i, paper in enumerate(papers, 1):
        authors_ieee = f"{paper['authors'][0]} et al." if len(paper['authors']) > 2 else ", ".join(paper['authors'])
        doc += f"[{i}] {authors_ieee}, \"{paper['title']},\" *arXiv preprint arXiv:{paper['id']}*, {paper['published'][:4]}.\n"
        
    doc += "\n### APA Format References\n"
    for paper in papers:
        authors_apa = f"{paper['authors'][0]} et al." if len(paper['authors']) > 2 else " & ".join(paper['authors'])
        doc += f"{authors_apa} ({paper['published'][:4]}). {paper['title']}. *arXiv preprint arXiv:{paper['id']}*.\n"
        
    return doc

def run_agentic_literature_review():
    if not os.path.exists(json_path):
        print_status("Error", f"Metadata file '{json_path}' not found. Please run 'python paper_fetcher.py' first.")
        sys.exit(1)
        
    with open(json_path, 'r', encoding='utf-8') as f:
        papers = json.load(f)
        
    if not papers:
        print_status("Warning", "No papers found to compile.")
        return
        
    print_header("GOOGLE RESEARCH ASSISTANT: REVIEW COMPILER")
    
    api_key = os.environ.get("ANTHROPIC_API_KEY")
    offline_mode = api_key is None
    review_content = ""
    
    if not offline_mode:
        print_status("AI Mode", "Connecting to Claude 3.5 Sonnet...")
        client = Anthropic()
        
        context_str = ""
        for i, paper in enumerate(papers, 1):
            context_str += f"Paper [{i}]:\n"
            context_str += f"Title: {paper['title']}\n"
            context_str += f"Authors: {', '.join(paper['authors'])}\n"
            context_str += f"Published: {paper['published']}\n"
            context_str += f"Abstract: {paper['summary']}\n"
            context_str += f"URL: {paper['pdf_url']}\n\n"
            
        prompt = (
            f"You are a Senior Academic Reviewer. Below are {len(papers)} papers on a target research topic.\n\n"
            f"CONTEXT:\n{context_str}\n"
            "TASK:\n"
            "Generate a highly professional, publication-ready literature review in Markdown format. "
            "Your output must contain these exact sections:\n"
            "1. # Executive Summary (Synthesize the theme of all papers)\n"
            "2. # Comparative Summary Table (Generate a markdown table showing Paper Number, Title, Core Authors, Year, and Methodology keyword)\n"
            "3. # Individual Paper Analyses (For each paper, summarize: Objective, Method, Key Results, and Limitations)\n"
            "4. # Literature Synthesis & Comparison (Identify connections, agreements, and disagreements among the papers)\n"
            "5. # References & Citations (Provide full citations for all papers in both IEEE and APA formats)\n\n"
            "Ensure the tone is academic, critical, and objective."
        )
        
        try:
            response = client.messages.create(
                model="claude-3-5-sonnet-20241022",
                max_tokens=3000,
                messages=[{"role": "user", "content": prompt}]
            )
            review_content = response.content[0].text
            print_status("Success", "Claude successfully generated the report.")
            
        except Exception as e:
            if "credit balance" in str(e).lower() or "billing" in str(e).lower():
                print_status("API Error", "Claude API credit balance is $0. Switching to Offline Mode...")
            else:
                print_status("API Error", f"Connection failed: {e}. Switching to Offline Mode...")
            review_content = compile_offline_literature_review(papers)
    else:
        review_content = compile_offline_literature_review(papers)
        
    os.makedirs('output', exist_ok=True)
    with open(output_review_path, 'w', encoding='utf-8') as f:
        f.write(review_content)
        
    print_header("COMPILATION SUCCESSFUL")
    print_status("Save", f"Literature review saved to: {output_review_path}\n")

if __name__ == '__main__':
    run_agentic_literature_review()
